// Code generated by goagen v1.3.0, DO NOT EDIT.
//
// API "cellar": Application User Types
//
// Command:
// $ goagen
// --design=github.com/podhmo/cellar/design
// --out=$(GOPATH)/src/github.com/podhmo/cellar
// --version=v1.3.0

package client
